/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Controllers;

import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JRResultSetDataSource;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperReport;

/**
 *
 * @author lalo
 */
public class GenerarDatos extends javax.swing.JFrame {

    /**
     * Creates new form GenerarDatos
     */
      ArrayList<String> fields=new ArrayList<>();
    public GenerarDatos() {
        Thread.currentThread().getName();
        initComponents();
        
        fields.add("<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n" +
"<jasperReport xmlns=\"http://jasperreports.sourceforge.net/jasperreports\" xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xsi:schemaLocation=\"http://jasperreports.sourceforge.net/jasperreports http://jasperreports.sourceforge.net/xsd/jasperreport.xsd\" name=\"report name\" pageWidth=\"595\" pageHeight=\"842\" columnWidth=\"535\" leftMargin=\"20\" rightMargin=\"20\" topMargin=\"20\" bottomMargin=\"20\" uuid=\"1f7a20fb-943c-48e0-8cf7-8a865131ab9b\">\n" +
"	<property name=\"ireport.zoom\" value=\"1.5\"/>\n" +
"	<property name=\"ireport.x\" value=\"0\"/>\n" +
"	<property name=\"ireport.y\" value=\"0\"/>\n" +
"	<style name=\"Column header\" forecolor=\"#666666\" fontName=\"Arial\" fontSize=\"12\" isBold=\"true\"/>\n" +
"	<parameter name=\"Titulo\" class=\"java.lang.String\"/>\n");
        /*
        fields.add("<jasperReport xmlns=\"http://jasperreports.sourceforge.net/jasperreports\" xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xsi:schemaLocation=\"http://jasperreports.sourceforge.net/jasperreports http://jasperreports.sourceforge.net/xsd/jasperreport.xsd\" name=\"report name\" pageWidth=\"595\" pageHeight=\"842\" columnWidth=\"535\" leftMargin=\"20\" rightMargin=\"20\" topMargin=\"20\" bottomMargin=\"20\" uuid=\"1f7a20fb-943c-48e0-8cf7-8a865131ab9b\">\n" +
        "");
        fields.add("<property name=\"ireport.zoom\" value=\"1.5\"/>");
        fields.add("<property name=\"ireport.x\" value=\"0\"/>");
        fields.add("<property name=\"ireport.y\" value=\"0\"/>");
        fields.add("<style name=\"Column header\" forecolor=\"#666666\" fontName=\"Arial\" fontSize=\"12\" isBold=\"true\"/>");
        fields.add("<parameter name=\"Titulo\" class=\"java.lang.String\"/>");
       */
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        jCheckBox4 = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Generar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jCheckBox1.setText("id");

        jCheckBox2.setText("nombres");
        jCheckBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox2ActionPerformed(evt);
            }
        });

        jCheckBox3.setText("apellidos");

        jCheckBox4.setText("domicilio");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCheckBox4)
                    .addComponent(jCheckBox1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCheckBox3)
                            .addComponent(jCheckBox2))
                        .addGap(88, 88, 88)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addComponent(jCheckBox1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jCheckBox2)
                        .addGap(18, 18, 18)
                        .addComponent(jCheckBox3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jCheckBox4)
                .addContainerGap(64, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
                                         
            String check="";
            
            if(jCheckBox1.isSelected()){
                check=jCheckBox1.getText();
                fields.add("<field name=\""+ jCheckBox1.getText() +"\" class=\"java.lang.String\"/>");
            }
            if(jCheckBox2.isSelected()){
                check+=","+jCheckBox2.getText();
                fields.add("<field name=\""+ jCheckBox2.getText() +"\" class=\"java.lang.String\"/>");
            }
            if(jCheckBox3.isSelected()){
                check+=","+jCheckBox3.getText();
                fields.add("<field name=\""+ jCheckBox3.getText() +"\" class=\"java.lang.String\"/>");
            }
            if(jCheckBox4.isSelected()){
                check+=","+jCheckBox4.getText();
                fields.add("<field name=\""+ jCheckBox4.getText() +"\" class=\"java.lang.String\"/>");
            }
            fields.add("<background>\n" +
                    "		<band splitType=\"Stretch\"/>\n" +
                    "	</background>\n" +
                    "	<title>\n" +
                    "		<band height=\"71\" splitType=\"Stretch\">\n" +
                    "			<textField>\n" +
                    "				<reportElement x=\"11\" y=\"19\" width=\"220\" height=\"32\" uuid=\"c73268ad-35b6-46d1-9547-530e9e3c6c91\"/>\n" +
                    "				<textElement>\n" +
                    "					<font fontName=\"Arial\" size=\"16\"/>\n" +
                    "				</textElement>\n" +
                    "				<textFieldExpression><![CDATA[$P{Titulo}]]></textFieldExpression>\n" +
                    "			</textField>\n" +
                    "			<image>\n" +
                    "				<reportElement x=\"433\" y=\"0\" width=\"70\" height=\"70\" uuid=\"76510011-bfc5-4c04-8aac-03468fc1cb50\"/>\n" +
                    "				<imageExpression><![CDATA[\"C:\\\\Users\\\\lalo\\\\Documents\\\\NetBeansProjects\\\\umai\\\\UmaiSystem\\\\img\\\\UmaiSystem.png\"]]></imageExpression>\n" +
                    "			</image>\n" +
                    "		</band>\n" +
                    "	</title>");
            
            fields.add("	<columnHeader>\n" +
                    "		<band height=\"31\" splitType=\"Stretch\">\n" +
                    "			<line>\n" +
                    "				<reportElement x=\"0\" y=\"27\" width=\"555\" height=\"1\" uuid=\"cd8683a6-074d-4578-9e7e-2b99647f8f7f\"/>\n" +
                    "			</line>\n");
            ///campos estaticos dentro del columHeader
            /*
            ***************************
            */
            int i=20;
            if(jCheckBox1.isSelected()){
                
                fields.add("<staticText>\n" +
                        "				<reportElement x=\""+i + "\" y=\"1\" width=\"80\" height=\"20\" uuid=\"42f3d6b2-739c-4f66-9197-6832fd4f9177\"/>\n" +
                        "				<text><![CDATA["+jCheckBox1.getText()+"]]></text>\n" +
                        "			</staticText>");
                i+=120;
            }
            if(jCheckBox2.isSelected()){
                
                fields.add("<staticText>\n" +
                        "				<reportElement x=\""+i+ "\" y=\"1\" width=\"80\" height=\"20\" uuid=\"42f3d6b2-739c-4f66-9197-6832fd4f9177\"/>\n" +
                        "				<text><![CDATA["+jCheckBox2.getText()+"]]></text>\n" +
                        "			</staticText>");
                i+=120;
            }
            if(jCheckBox3.isSelected()){
                
                fields.add("<staticText>\n" +
                        "				<reportElement x=\""+i+"\" y=\"1\" width=\"80\" height=\"20\" uuid=\"42f3d6b2-739c-4f66-9197-6832fd4f9177\"/>\n" +
                        "				<text><![CDATA["+jCheckBox3.getText()+"]]></text>\n" +
                        "			</staticText>");
                i+=120;
            }
            if(jCheckBox4.isSelected()){
                
                fields.add("<staticText>\n" +
                        "				<reportElement x=\" "+i+ "\" y=\"1\" width=\"80\" height=\"20\" uuid=\"42f3d6b2-739c-4f66-9197-6832fd4f9177\"/>\n" +
                        "				<text><![CDATA["+jCheckBox4.getText()+"]]></text>\n" +
                        "			</staticText>");
                i+=120;
            }
            
            /*
            **************************
            */
            
            fields.add("		</band>\n" +
                    "	</columnHeader>\n" +
                    "	<detail>\n" +
                    "		<band height=\"27\" splitType=\"Stretch\">\n" +
                    "			<line>\n" +
                    "				<reportElement x=\"0\" y=\"21\" width=\"555\" height=\"1\" uuid=\"1a20fa04-0535-4ed5-ae3f-3b53658956e9\"/>\n" +
                    "			</line>\n");
            /*
            *****************************************************
            campos para vaciar
            */
            
            int j=20;
            if(jCheckBox1.isSelected()){
                fields.add("			<textField>\n" +
                        "				<reportElement x=\""+j+"\" y=\"2\" width=\"80\" height=\"20\" uuid=\"a05c33b6-f41d-4b2c-8585-d1c578197d01\"/>\n" +
                        "				<textFieldExpression><![CDATA[$F{"+jCheckBox1.getText()+"}]]></textFieldExpression>\n" +
                        "			</textField>");
                j+=120;
                
            }
            if(jCheckBox2.isSelected()){
                fields.add("			<textField>\n" +
                        "				<reportElement x=\""+j+"\" y=\"2\" width=\"80\" height=\"20\" uuid=\"a05c33b6-f41d-4b2c-8585-d1c578197d01\"/>\n" +
                        "				<textFieldExpression><![CDATA[$F{"+jCheckBox2.getText()+"}]]></textFieldExpression>\n" +
                        "			</textField>");
                j+=120;
            }
            if(jCheckBox3.isSelected()){
                fields.add("			<textField>\n" +
                        "				<reportElement x=\""+j+ "\" y=\"2\" width=\"80\" height=\"20\" uuid=\"a05c33b6-f41d-4b2c-8585-d1c578197d01\"/>\n" +
                        "				<textFieldExpression><![CDATA[$F{"+jCheckBox3.getText()+"}]]></textFieldExpression>\n" +
                        "			</textField>");
                j+=120;
            }
            if(jCheckBox4.isSelected()){
                fields.add("			<textField>\n" +
                        "				<reportElement x=\""+j +"\" y=\"2\" width=\"80\" height=\"20\" uuid=\"a05c33b6-f41d-4b2c-8585-d1c578197d01\"/>\n" +
                        "				<textFieldExpression><![CDATA[$F{"+jCheckBox4.getText()+"}]]></textFieldExpression>\n" +
                        "			</textField>");
                j+=120;
            }
            
            /*
            ****************************************************
            */
            fields.add("		</band>\n" +
                    "	</detail>\n" +
                    "	<columnFooter>\n" +
                    "		<band height=\"16\" splitType=\"Stretch\"/>\n" +
                    "	</columnFooter>\n" +
                    "	<pageFooter>\n" +
                    "		<band height=\"21\" splitType=\"Stretch\">\n" +
                    "			<textField>\n" +
                    "				<reportElement style=\"Column header\" x=\"433\" y=\"0\" width=\"80\" height=\"20\" forecolor=\"#666666\" uuid=\"70d59fa6-c1d3-4c22-9c33-3ee5a820ea7c\"/>\n" +
                    "				<textElement>\n" +
                    "					<font fontName=\"Arial\" size=\"10\" isBold=\"false\"/>\n" +
                    "				</textElement>\n" +
                    "				<textFieldExpression><![CDATA[\"Page \"+$V{PAGE_NUMBER}+\" of\"]]></textFieldExpression>\n" +
                    "			</textField>\n" +
                    "			<textField>\n" +
                    "				<reportElement style=\"Column header\" x=\"513\" y=\"0\" width=\"42\" height=\"20\" forecolor=\"#666666\" uuid=\"b4b65a9c-9cba-45f8-b18e-0a30f1871128\"/>\n" +
                    "				<textElement>\n" +
                    "					<font fontName=\"Arial\" size=\"10\" isBold=\"false\"/>\n" +
                    "				</textElement>\n" +
                    "				<textFieldExpression><![CDATA[\" \" + $V{PAGE_NUMBER}]]></textFieldExpression>\n" +
                    "			</textField>\n" +
                    "			<textField>\n" +
                    "				<reportElement x=\"0\" y=\"1\" width=\"197\" height=\"20\" uuid=\"d461d965-02f6-413e-93ba-517fd047a005\"/>\n" +
                    "				<textFieldExpression><![CDATA[new java.util.Date()]]></textFieldExpression>\n" +
                    "			</textField>\n" +
                    "		</band>\n" +
                    "	</pageFooter>\n" +
                    "</jasperReport>");
            System.out.println(check);
            try {
                plantilla(fields);
            } catch (IOException ex) {
                Logger.getLogger(GenerarDatos.class.getName()).log(Level.SEVERE, null, ex);
            }
            String sql="Select "+check+" from datos ";
           
           
            System.out.println(Thread.currentThread().getName());
        generarPDF(sql);
            
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jCheckBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GenerarDatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GenerarDatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GenerarDatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GenerarDatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GenerarDatos().setVisible(true);
            }
        });
    }
public static void plantilla(ArrayList<String> datos) throws IOException{
        String ruta = "src/archivo1.jrxml";
       
        File archivo = new File(ruta);
        BufferedWriter bw;
        
            bw = new BufferedWriter(new FileWriter(archivo));
            //bw.write("Acabo de crear el fichero de texto.");
            for (int i = 0; i <datos.size(); i++) {
                bw.write(datos.get(i)+"\r");
            }
        
        bw.close();
        
        
    }

public static void generarPDF(String sql){
    System.out.println("generar pdf");
    try{
                
                //String archivo = "/src/archivo1.jrxml";
                String archivo = "./src/reportes/archivo2.jrxml";
            JasperReport masterReport= null;
            try {
                System.out.println("entro??");
                masterReport= JasperCompileManager.compileReport(archivo);
                JasperCompileManager.compileReportToFile(
                archivo,//the path to the jrxml file to compile
                "./reportes/HIHI22.jasper");//the path and name we want to save the compiled file 
                System.out.println("Compilacion correcta");
            } catch (JRException e) {
               
                System.err.println(e.getCause());
            }
            System.out.println("hi ");
            /*
             InputStream archivo2=new FileInputStream("src/reportes/HIHI.jasper");
        JasperReport reporte = (JasperReport) JRLoader.loadObject(archivo2);
        Map param=new HashMap();
        param.put("Titulo","Intento de compilar");
        JasperPrint jasperPrint = JasperFillManager.fillReport(reporte,param, resultSetDataSource); // este es para cuando hace una plantilla desde cero
      //  JasperPrint jasperPrint = JasperFillManager.fillReport(reporte,param,conexion); // este es una plantilla ya predefinida
        Exporter exporter=new JRPdfExporter();
           
        exporter.setExporterInput(new SimpleExporterInput(jasperPrint));
        exporter.setExporterOutput(new SimpleOutputStreamExporterOutput("src/reportes/reporte_plantilla.pdf"));
        System.out.println("éxito reporte creado");
        
        
        exporter.exportReport();   
                    */
        }catch (Exception ex){
           System.out.println("que?"+ex.getCause());
        }
}


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox4;
    // End of variables declaration//GEN-END:variables
}
